//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Framework.Controls;
using System.Collections.Generic;
namespace Framework.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("choppinTREES")]
        public string GuildTitle {
            get {
                return ((string)(this["GuildTitle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CHOPPIN\' TREES")]
        public string GuildName {
            get {
                return ((string)(this["GuildName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mug\'thol")]
        public string Realm {
            get {
                return ((string)(this["Realm"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horde")]
        public string Faction {
            get {
                return ((string)(this["Faction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public List<ExternalLink> ExternalLinks {
            get {
                if (this["ExternalLinks"] == null)
                {
                    this["ExternalLinks"] = new List<ExternalLink>()
                    {
                        new ExternalLink()
                        {
                            Name = "Raid logs",
                            URL = "#",
                            NewWindow = true
                        },
                        new ExternalLink()
                        {
                            Name = "Armory",
                            URL = "http://us.battle.net/wow/en/guild/mugthol/CHOPPIN_TREES/",
                            NewWindow = true
                        }
                    };
                }
                return ((List<ExternalLink>)(this["ExternalLinks"]));
            }
        }
    }
}
